auth_app/urls.py
from . import views
from django.views.decorators.csrf import csrf_exempt
from django.urls import path

app_name = 'auth_app'

urlpatterns = [
    path("login/", views.LoginView.as_view(), name="login"),
   path('logout/', views.logout_view, name='logout'),
    path("register/", views.Register.as_view(), name="register"),
    path("username-validation/", csrf_exempt(views.username_validation), name="user-validation"),
    path("email-validation/", csrf_exempt(views.email_validation), name="email-validation"),
    path("activate/<uidb64>/<token>/", views.VerificationView.as_view(), name="activate"),
    
]

expence_tracker/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("expenses.urls")),
    path("preferences/", include("user_preferences.urls")),
    path("auth/", include("auth_app.urls")),
]

expenses/urls.py
from django.urls import path
from django.views.decorators.csrf import csrf_exempt
from . import views

app_name = 'expenses'

urlpatterns = [
    path("", views.index, name="expenses"),
    path("add_expenses/", views.add_expenses, name="add-expenses"),
    path("edit/<int:id>/", views.edit_expenses, name="edit-expenses"),
    path("delete/<int:id>/", views.delete_expense, name="delete-expenses"),
    path("search-expenses/", csrf_exempt(views.get_search_expense), name="search-expenses"),
]

user_preferences/urls.py
from django.urls import path
from . import views


app_name = 'user_preferences'

urlpatterns = [
    path("", views.index, name="preferences"),
]

templates/partials/_messages.html
<!-- {% if messages %}
<div class="messages">
    {% for message in messages %}
    <div>{% if message.tags %} class="alert alert-sm alert-{{ message.tags }}"{% endif %}>
        {{ message }}
    </div>
    {% endfor %}
</ul>
{% endif %} -->

{% for message in messages %}
    <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
        {{ message }}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
{% endfor %}

templates/partials/_sidebar.html
{% load static %}

<div class="sidebar border border-right col-md-3 col-lg-2 p-0 bg-body-tertiary">
    <div class="offcanvas-md offcanvas-end bg-body-tertiary" tabindex="-1" id="sidebarMenu" aria-labelledby="sidebarMenuLabel">
      <div class="offcanvas-header">
        <h5 class="offcanvas-title" id="sidebarMenuLabel">Company name</h5>
        <button type="button" class="btn-close" data-bs-dismiss="offcanvas" data-bs-target="#sidebarMenu" aria-label="Close"></button>
      </div>
      <div class="offcanvas-body d-md-flex flex-column p-0 pt-lg-3 overflow-y-auto">
        <ul class="nav flex-column">
          <li class="nav-item">
            <a class="nav-link d-flex align-items-center gap-2 active" aria-current="page" href="#">
              <svg class="bi"><use xlink:href="#house-fill"/></svg>
              Dashboard
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link d-flex align-items-center gap-2" href="{% url 'expenses:expenses' %}">
              <svg class="bi"><use xlink:href="#file-earmark"/></svg>
              Expenses
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link d-flex align-items-center gap-2" href="#">
              <svg class="bi"><use xlink:href="#cart"/></svg>
              income
            </a>
          </li>
        </ul>

        <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-body-secondary text-uppercase">
          <span>Summary</span>
          <a class="link-secondary" href="#" aria-label="Add a new report">
            <svg class="bi"><use xlink:href="#plus-circle"/></svg>
          </a>
        </h6>
        <ul class="nav flex-column mb-auto">
          <li class="nav-item">
            <a class="nav-link d-flex align-items-center gap-2" href="#">
              <svg class="bi"><use xlink:href="#file-earmark-text"/></svg>
              Expenses Summary
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link d-flex align-items-center gap-2" href="#">
              <svg class="bi"><use xlink:href="#file-earmark-text"/></svg>
              Income Summary
            </a>
          </li>
        </ul>
        <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-body-secondary text-uppercase">
          <span>Setting</span>
          <a class="link-secondary" href="#" aria-label="Add a new report">
            <svg class="bi"><use xlink:href="#plus-circle"/></svg>
          </a>
        </h6>
        <ul class="nav flex-column mb-auto">
          <li class="nav-item">
            <a class="nav-link d-flex align-items-center gap-2" href="#">
              <svg class="bi"><use xlink:href="#gear-wide-connected"/></svg>
              General
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link d-flex align-items-center gap-2" href="{% url 'user_preferences:preferences' %}">
              <svg class="bi"><use xlink:href="#door-closed"/></svg>
              Account
            </a>
          </li>
        </ul>
        <ul class="nav flex-column mb-auto">
          <li class="nav-item">
            <a class="nav-link d-flex align-items-center gap-2" href="{% url 'auth_app:logout' %}">
              <svg class="bi"><use xlink:href="#door-closed"/></svg>
              Sign out
            </a>
          </li>
        </ul>
      </div>
    </div>
  </div>