auth_app/urls.py
from . import views
from django.views.decorators.csrf import csrf_exempt
from django.urls import path

app_name = 'auth_app'

urlpatterns = [
    path("login/", views.LoginView.as_view(), name="login"),
   path('logout/', views.logout_view, name='logout'),
    path("register/", views.Register.as_view(), name="register"),
    path("username-validation/", csrf_exempt(views.username_validation), name="user-validation"),
    path("email-validation/", csrf_exempt(views.email_validation), name="email-validation"),
    path("activate/<uidb64>/<token>/", views.VerificationView.as_view(), name="activate"),
    
]

expence_tracker/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("expenses.urls")),
    path("preferences/", include("user_preferences.urls")),
    path("auth/", include("auth_app.urls")),
]

expenses/urls.py
from django.urls import path
from django.views.decorators.csrf import csrf_exempt
from . import views

app_name = 'expenses'

urlpatterns = [
    path("", views.index, name="expenses"),
    path("add_expenses/", views.add_expenses, name="add-expenses"),
    path("edit/<int:id>/", views.edit_expenses, name="edit-expenses"),
    path("delete/<int:id>/", views.delete_expense, name="delete-expenses"),
    path("search-expenses/", csrf_exempt(views.get_search_expense), name="search-expenses"),
]

expenses/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.timezone import now


class Expense(models.Model):
    amount = models.FloatField()
    date = models.DateField(default=now)
    description = models.TextField()
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    category = models.ForeignKey("Category", on_delete=models.CASCADE)

    def __str__(self):
        return self.owner.username + " " + "Expenses"

    class Meta:
        ordering = ["-date"]


class Category(models.Model):
    name = models.CharField(max_length=255)

    class Meta:
        verbose_name = "Category"

    def __str__(self):
        return self.name

expenses/views.py
from django.shortcuts import redirect, render
from django.contrib.auth.decorators import login_required
from .models import Category, Expense
from django.http import JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.core.paginator import Paginator
import json


@login_required
def index(request):
    current_user = request.user
    expenses = Expense.objects.filter(owner=current_user)
    paginator = Paginator(expenses, 5)
    page_number = request.GET.get("page")

    # construct page_obj
    page_obj = Paginator.get_page(paginator, page_number)

    context = {
        "expenses": expenses,
        "page_obj": page_obj,
    }

    return render(request, "expenses/index.html", context)


def add_expenses(request):
    categories = Category.objects.all()

    if request.method == "POST":
        amount = request.POST.get("amount")
        description = request.POST.get("description")
        category = request.POST.get("category")
        date = request.POST.get("date")

        if not amount:
            messages.error(request, "Amount is required")
        elif not description:
            messages.error(request, "description is required")
        elif not date:
            messages.error(request, "date is required")
        else:
            Expense.objects.create(
                owner=request.user,
                amount=amount,
                description=description,
                category=category,
                date=date,
            )
            messages.success(request, "expenses created successfully")
            return redirect("expenses:expenses")
    context = {
        "categories": categories,
        "field_values": request.POST,
    }

    return render(request, "expenses/add_expenses.html", context)


# Edit expenses
def edit_expenses(request, id):
    expense = get_object_or_404(Expense, pk=id, owner=request.user)
    categories = Category.objects.all()

    if request.method == "POST":
        amount = request.POST.get("amount")
        description = request.POST.get("description")
        category = request.POST.get("category")
        date = request.POST.get("date")

        if not amount:
            messages.error(request, "Amount is required")
        elif not description:
            messages.error(request, "description is required")
        elif not date:
            messages.error(request, "date is required")
        else:
            # Update the expense object with the new data
            expense.amount = amount
            expense.description = description
            expense.category = category
            expense.date = date
            expense.save()

            # import pdb; pdb.set_trace()

            messages.success(request, "Expense updated successfully")
            return redirect("expenses:expenses")
    context = {
        "expense": expense,
        "categories": categories,
    }

    return render(request, "expenses/edit_expenses.html", context)


def delete_expense(request, id):
    expense = get_object_or_404(Expense, pk=id)

    if request.method == "POST":
        expense.delete()
        messages.success(request, "Expense record deleted successfully")
        return redirect("expenses:expenses")  # Redirect to the expenses list page

    context = {
        "expense": expense,
    }

    return render(request, "expenses/delete.html", context)


# search expense request Api request
def get_search_expense(request):
    if request.method == "POST":
        data = json.loads(request.body)
        search_data = data.get("searchText", "")

        expenses = Expense.objects.filter(amount__istartswith=search_data) | Expense.objects.filter(description__icontains=search_data)| Expense.objects.filter(date__istartswith=search_data)| Expense.objects.filter(category__name__istartswith=search_data)
        

        search_values = expenses.values()

        print(search_values)

    return JsonResponse(list(search_values), safe=False)

expenses/templates/expenses/add_expenses.html
{% extends 'base.html' %} {% block content %}
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{% url 'expenses:expenses' %}">My Expenses</a></li>
    <li class="breadcrumb-item active" aria-current="page">Add Expenses</li>
  </ol>
</nav>

<div class="card">
  <div class="card-body">
    {% include 'partials/_messages.html' %}
    <form action="{% url 'expenses:add-expenses' %}" method="POST">
      {% csrf_token %}
      <div class="mb-3">
        <label for="exampleFormControlInput1" class="form-label">Amount</label>
        <input
          name="amount"
          type="number"
          class="form-control"
          value="{{field_values.amount}}"
          id="exampleFormControlInput1"
        />
      </div>
      <div class="mb-3">
        <label for="exampleFormControlTextarea1" class="form-label"
          >Description</label
        >
        <textarea
          name="description"
          class="form-control"
          id="exampleFormControlTextarea1"
          rows="3"
        ></textarea>
      </div>
      <div class="mt-3">
        <label for="category" class="form-label">Category</label>
        <select class="form-select" aria-label="Small select example" name="category">
          <option selected>Categories</option>
            {% for category in categories %}
            <option value="{{ category.name }}">{{category.name}}</option>
            {% endfor %}
        </select>
      </div>
      <div class="mt-3">
        <label for="exampleFormControlInput1" class="form-label">Date</label>
        <input
          type="date"
          name="date"
          value="{{field_values.date}}"
          class="form-control"
          id="exampleFormControlInput1"
          placeholder="name@example.com"
        />
      </div>
      <div class="d-grid gap-2 mt-3">
        <button class="btn btn-primary" type="submit">Submit</button>
      </div>
    </form>
  </div>
</div>
{% endblock %}

expenses/templates/expenses/delete.html
{% extends 'base.html' %}



{% block content %}
<div class="form-container-delete">
    <form action="{% url 'expenses:delete-expenses' expense.id %}" method="POST">
        {% csrf_token %}
        <h5>Are you sure you want to delete this expense?</h5>
        <div class="delete-cancel mt-4">
            <a class="btn btn-primary w-50" href="{% url 'expenses:expenses' %}">Cancel</a>
            <button type="submit" class="btn btn-danger w-50">Delete</button>
        </div>
    </form>
</div>    
{% endblock %}
    

expenses/templates/expenses/edit_expenses.html
{% extends 'base.html' %}
{% block content %}
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="#">My Expenses</a></li>
      <li class="breadcrumb-item active" aria-current="page">Add Expenses</li>
    </ol>
  </nav>
  
  <div class="card">        
    <div class="card-body">
      {% include 'partials/_messages.html' %}
      <form action="{% url 'expenses:edit-expenses' expense.id %}" method="POST">
        {% csrf_token %}
        <div class="mb-3">
          <label for="exampleFormControlInput1" class="form-label">Amount</label>
          <input
            name="amount"
            type="number"
            class="form-control"
            value="{{expense.amount}}"
            id="exampleFormControlInput1"
          />
        </div>
        <div class="mb-3">
          <label for="exampleFormControlTextarea1" class="form-label"
            >Description</label
          >
          <textarea
            name="description"
            class="form-control"
            id="exampleFormControlTextarea1"
            rows="3"
          >{{ expense.description }}</textarea>
        </div>
        <div class="mt-3">
          <label for="category" class="form-label">Category</label>
          <select class="form-select" aria-label="Small select example" name="category">
            <option selected>{{ expense.category }}</option>
              {% for category in categories %}
              <option value="{{ category.name }}">{{category.name}}</option>
              {% endfor %}
          </select>
        </div>
        <div class="mt-3">
          <label for="exampleFormControlInput1" class="form-label">Date</label>
          <input
            type="date"
            name="date"
            alue="{% if expense.date %}{{expense.date|date:'Y-m-d'}}{% endif %}"
            class="form-control"
            id="exampleFormControlInput1"
            placeholder="dd/mm/yyyy"
          />
        </div>
        <div class="d-grid gap-2 mt-3">
          <button class="btn btn-primary" type="submit">Submit</button>
        </div>
      </form>
    </div>
  </div>
    
{% endblock %}

expenses/templates/expenses/index.html
{% extends 'base.html' %} {% block content %} {% load static  %}{% load humanize %}
<div class="expense-wrapper mt-5">
  {% include 'partials/_messages.html' %}
  <div class="wrapper-index d-flex justify-content-between">
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="#">Expenses</a></li>
        <li class="breadcrumb-item active" aria-current="page">My Expenses</li>
      </ol>
    </nav>
    <form class="d-flex" role="search">
      {% csrf_token %}
      <input class="form-control me-2" name="searchText" id="searchInput" placeholder="Search">
    </form>
    <a class="add-button-expense" href="{% url 'expenses:add-expenses' %}"
      >Add Expenses</a
    >
  </div>


{% if expenses.count == 0 %}
<div class="center-text">
    <h2>You haven't recorded any expenses</h2>
</div>
        {% else %}
        <div class="expenses">
            <table class="table mt-4 table-show">
              <thead class="table-dark">
                <tr>
                  <th scope="col">Amount</th>
                  <th scope="col">Category</th>
                  <th scope="col">Description</th>
                  <th scope="col">Date</th>
                  <th class="text-center" scope="col">Update</th>
                  <th class="text-center" scope="col">Delete</th>
                </tr>
              </thead>
              <tbody>
                {% for expense in page_obj %}
                <tr>
                  <td>{{expense.amount|floatformat:2|intcomma }}</td>
                  <td>{{expense.category}}</td>
                  <td>{{expense.description}}</td>
                  <td>{{expense.date}}</td>
                  <td class="text-center"><a href="{% url 'expenses:edit-expenses' expense.id %}"><i class="fa-solid fa-pen-to-square"></i></a></td>
                  <td class="text-center"><a href="{% url 'expenses:delete-expenses' expense.id %}"><i class="fa-solid fa-trash-can" style="color: #ffffff; text-align:center;"></i></a></td>

                </tr>
            </tbody>
            {% endfor %}
    </table>

    <table class="table table-output mt-4">
      <thead class="table-dark">
        <tr>
          <th scope="col">Amount</th>
          <th scope="col">Category</th>
          <th scope="col">Description</th>
          <th scope="col">Date</th>
          <th class="text-center" scope="col">Update</th>
          <th class="text-center" scope="col">Delete</th>
        </tr>
      </thead>
      <tbody class="table-body">
        {% for expense in page_obj %}
        <tr>
          <td>{{expense.amount|floatformat:2|intcomma }}</td>
          <td>{{expense.category}}</td>
          <td>{{expense.description}}</td>
          <td>{{expense.date}}</td>
          <td class="text-center"><a href="{% url 'expenses:edit-expenses' expense.id %}"><i class="fa-solid fa-pen-to-square"></i></a></td>
          <td class="text-center"><a href="{% url 'expenses:delete-expenses' expense.id %}"><i class="fa-solid fa-trash-can" style="color: #ffffff; text-align:center;"></i></a></td>

        </tr>
    </tbody>
    {% endfor %}
</table>
  </div>

    <div class="paginator-class-wrapper">
      <div class="paginator-class">
        Showing page {{page_obj.number}} of {{page_obj.paginator.num_pages}} pages
      </div>
      <div class="page-navigation">
          <ul class="pagination justify-content-center">
              {% if page_obj.has_previous %}
                  <li {% if page_obj == 1  %} class="page-item active" {% endif %}>
                      <a class="page-link" href="?page=1">&laquo; 1</a></li>
                  <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous
                      </a>
                  </li>
              {% endif %}
  
              {% if page_obj.has_next %}
                  <li class="page-item">
                      <a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a>
                  </li>
                  <li class="page-item">
                      <a class="page-link" href="?page={{ paginator.num_pages }}">{{ page_obj.paginator.num_pages }}  </a>
                  </li>
              {% endif %}
          </ul>
      </div>
    </div>
{% endif %}
</div>

<script src="{% static 'js/expense_search.js' %}"></script>
{% endblock content %}